# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_rename.ui'
#
# Created: Wed Sep 28 00:39:35 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(621, 592)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setAutoFillBackground(False)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_inputPath = QtGui.QLabel(Dialog)
        self.label_inputPath.setObjectName("label_inputPath")
        self.verticalLayout.addWidget(self.label_inputPath)
        self.inp_path = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(11)
        self.inp_path.setFont(font)
        self.inp_path.setAcceptDrops(True)
        self.inp_path.setObjectName("inp_path")
        self.verticalLayout.addWidget(self.inp_path)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_renameSection = QtGui.QLabel(Dialog)
        self.label_renameSection.setObjectName("label_renameSection")
        self.verticalLayout_2.addWidget(self.label_renameSection)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label_oldText = QtGui.QLabel(Dialog)
        self.label_oldText.setObjectName("label_oldText")
        self.gridLayout.addWidget(self.label_oldText, 0, 0, 1, 1)
        self.inp_oldText = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inp_oldText.setFont(font)
        self.inp_oldText.setObjectName("inp_oldText")
        self.gridLayout.addWidget(self.inp_oldText, 0, 1, 1, 1)
        self.label_NewText = QtGui.QLabel(Dialog)
        self.label_NewText.setObjectName("label_NewText")
        self.gridLayout.addWidget(self.label_NewText, 1, 0, 1, 1)
        self.inp_newText = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inp_newText.setFont(font)
        self.inp_newText.setObjectName("inp_newText")
        self.gridLayout.addWidget(self.inp_newText, 1, 1, 1, 1)
        self.btn_rename = QtGui.QPushButton(Dialog)
        self.btn_rename.setAutoDefault(False)
        self.btn_rename.setDefault(False)
        self.btn_rename.setFlat(False)
        self.btn_rename.setObjectName("btn_rename")
        self.gridLayout.addWidget(self.btn_rename, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressInfo = QtGui.QLabel(Dialog)
        self.progressInfo.setObjectName("progressInfo")
        self.horizontalLayout.addWidget(self.progressInfo)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.table = QtGui.QTableWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.table.setFont(font)
        self.table.setAutoFillBackground(False)
        self.table.setFrameShape(QtGui.QFrame.NoFrame)
        self.table.setFrameShadow(QtGui.QFrame.Plain)
        self.table.setLineWidth(1)
        self.table.setAutoScroll(False)
        self.table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table.setTabKeyNavigation(False)
        self.table.setProperty("showDropIndicator", True)
        self.table.setDragEnabled(False)
        self.table.setDragDropOverwriteMode(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setWordWrap(True)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(100)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.table, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.label_inputPath.setBuddy(self.inp_path)
        self.label_oldText.setBuddy(self.inp_oldText)
        self.label_NewText.setBuddy(self.inp_newText)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.btn_rename, QtCore.SIGNAL("released()"), self.table.scrollToTop)
        QtCore.QObject.connect(self.btn_rename, QtCore.SIGNAL("released()"), self.progressBar.reset)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.inp_path, self.inp_oldText)
        Dialog.setTabOrder(self.inp_oldText, self.inp_newText)
        Dialog.setTabOrder(self.inp_newText, self.table)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Batch Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_inputPath.setText(QtGui.QApplication.translate("Dialog", "Source Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_renameSection.setText(QtGui.QApplication.translate("Dialog", "For all files in the source folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_oldText.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p align=\"right\">Replace this:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NewText.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p align=\"right\">With this:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_rename.setText(QtGui.QApplication.translate("Dialog", "Rename!", None, QtGui.QApplication.UnicodeUTF8))
        self.progressInfo.setText(QtGui.QApplication.translate("Dialog", "0/0 processed", None, QtGui.QApplication.UnicodeUTF8))
        self.table.setSortingEnabled(False)
        self.table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Before", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "After", None, QtGui.QApplication.UnicodeUTF8))

